import { MethodCategory } from "@/types";

export const mockMethodCategories: MethodCategory[] = [
  {
    id: "general",
    name: "General",
    iconName: "Sun",
    methods: [
      { id: "llm", name: "LLM" },
      { id: "transformer", name: "Transformer" },
      { id: "fine-tuning", name: "Fine-tuning" },
      { id: "multi-head-attention", name: "Multi-head Attention" },
      { id: "softmax", name: "Softmax" },
      { id: "layer-normalization", name: "Layer Normalization" },
      { id: "mac-tuning", name: "Mac-tuning" },
      { id: "rlhf", name: "RLHF" },
      { id: "lora", name: "LoRA" },
      { id: "pre-training", name: "Pre-training" },
      { id: "chain-of-thought-(cot)", name: "Chain-of-Thought (CoT)" },
      { id: "adam", name: "Adam" },
      { id: "dropout", name: "Dropout" },
      { id: "embedding", name: "Embedding" }
    ],
  },
  {
    id: "language",
    name: "Language",
    iconName: "MessageSquare",
    methods: [
      { id: "bert", name: "BERT" },
      { id: "gpt", name: "GPT" },
      { id: "t5", name: "T5" },
      { id: "rag", name: "RAG" },
      { id: "seq2seq", name: "Seq2Seq" },
      { id: "attention", name: "Attention" },
      { id: "mamba-2", name: "Mamba-2" },
      { id: "performer", name: "Performer" },
      { id: "bleu", name: "BLEU" },
      { id: "rouge", name: "ROUGE" },
      { id: "fasttext", name: "fastText" },
      { id: "speculative-decoding", name: "Speculative Decoding" },
      { id: "sliding-window-attention", name: "Sliding Window Attention" },
      { id: "gated-deltanet", name: "Gated DeltaNet" }
    ],
  },
  {
    id: "vision",
    name: "Vision",
    iconName: "Eye",
    methods: [
      { id: "clip", name: "CLIP" },
      { id: "llava", name: "LLaVA" },
      { id: "vision-transformer", name: "Vision Transformer" },
      { id: "sam", name: "SAM" },
      { id: "dino", name: "DINO" },
      { id: "resnet", name: "ResNet" },
      { id: "u-net", name: "U-Net" },
      { id: "convnext", name: "ConvNeXt" },
      { id: "mask-r-cnn", name: "Mask R-CNN" },
      { id: "yolo", name: "YOLO" },
      { id: "nerf", name: "NeRF" },
      { id: "vit", name: "ViT" },
      { id: "r-cnn", name: "R-CNN" },
      { id: "swin-transformer", name: "Swin Transformer" }
    ],
  },
  {
    id: "audio-speech",
    name: "Audio & Speech",
    iconName: "AudioWaveform",
    methods: [
      { id: "whisper", name: "Whisper" },
      { id: "wavenet", name: "WaveNet" },
      { id: "conformer", name: "Conformer" },
      { id: "soundstream", name: "SoundStream" },
      { id: "rnn-transducer", name: "RNN-Transducer" },
      { id: "wav2vec", name: "Wav2Vec" },
      { id: "fast-conformer", name: "Fast Conformer" },
      { id: "neural-audio-codec", name: "Neural Audio Codec" },
      { id: "spectrogram", name: "Spectrogram" },
      { id: "tdt", name: "TDT" }
    ],
  },
  {
    id: "agents",
    name: "Agents",
    iconName: "Bot",
    methods: [
      { id: "react", name: "ReAct" },
      { id: "mcp", name: "MCP" },
      { id: "function-calling", name: "Function Calling" },
      { id: "agent-skills", name: "Agent Skills" },
      { id: "multi-turn", name: "Multi-turn" },
      { id: "tool-use", name: "Tool Use" },
      { id: "autogpt", name: "AutoGPT" },
      { id: "agent-frameworks", name: "Agent Frameworks" },
      { id: "planning", name: "Planning" },
      { id: "memory", name: "Memory" }
    ],
  },
  {
    id: "reasoning",
    name: "Reasoning",
    iconName: "Brain",
    methods: [
      { id: "chain-of-thought-(cot)", name: "Chain-of-Thought (CoT)" },
      { id: "tree-of-thoughts", name: "Tree of Thoughts" },
      { id: "grpo", name: "GRPO" },
      { id: "reasoning-model", name: "Reasoning Model" },
      { id: "self-refine", name: "Self-Refine" },
      { id: "reflection", name: "Reflection" },
      { id: "deep-research", name: "Deep Research" },
      { id: "xavier-initialization", name: "Xavier Initialization" },
      { id: "context-rot", name: "Context Rot" },
      { id: "test-time-compute", name: "Test-time Compute" }
    ],
  },
  {
    id: "training",
    name: "Training",
    iconName: "GraduationCap",
    methods: [
      { id: "pre-training", name: "Pre-training" },
      { id: "fine-tuning", name: "Fine-tuning" },
      { id: "peft", name: "PEFT" },
      { id: "qlora", name: "QLoRA" },
      { id: "lora", name: "LoRA" },
      { id: "prompt-engineering", name: "Prompt Engineering" },
      { id: "data-augmentation", name: "Data Augmentation" },
      { id: "curriculum-learning", name: "Curriculum Learning" },
      { id: "teacher-forcing", name: "Teacher Forcing" },
      { id: "label-smoothing", name: "Label Smoothing" }
    ],
  },
  {
    id: "optimization",
    name: "Optimization",
    iconName: "SlidersHorizontal",
    methods: [
      { id: "adam", name: "Adam" },
      { id: "adamw", name: "AdamW" },
      { id: "sgd", name: "SGD" },
      { id: "adafactor", name: "Adafactor" },
      { id: "weight-decay", name: "Weight Decay" },
      { id: "gradient-clipping", name: "Gradient Clipping" },
      { id: "learning-rate-scheduler", name: "Learning Rate Scheduler" },
      { id: "cosine-annealing", name: "Cosine Annealing" },
      { id: "batch-normalization", name: "Batch Normalization" },
      { id: "dropout", name: "Dropout" }
    ],
  }
];
